### ISSUE TITLE
Running on Apple Silicon

### ISSUE THREAD

**Issue by BjoernRave** [ivanlonel/postgis-with-extensions#30]
Is it possible the docker container is not running on apple silicon yet?

When trying to start it up in a docker-compose

```
services:
  db:
    image: ivanlonel/postgis-with-extensions
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
      - 
```

 I get:
`no matching manifest for linux/arm64/v8 in the manifest list entries`
